package com.bizuno.dtos.business;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Setter
@Getter
public class CreateReportRequestDTO {
    @NotNull(message = "Report type is required")
    @Size(max = 50, message = "Report type must not exceed 50 characters")
    private String reportType;

    @NotBlank(message = "Title is required")
    @Size(max = 200, message = "Title must not exceed 200 characters")
    private String title;

    @Size(max = 100, message = "Generated by must not exceed 100 characters")
    private String generatedBy;

    @NotNull(message = "Generated date is required")
    @JsonFormat(pattern = "dd-MM-yyyy HH:mm:ss")
    private LocalDateTime generatedAt;

    @Size(max = 500, message = "File URL must not exceed 500 characters")
    private String fileUrl;

    private String paramsJson;
}
